spring:
  application:
    name: cloudbalance

  config:
    import: optional:file:process.env[.properties]

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  redis:
    host: localhost
    port: 6379

jwt:
  secret: ${JWT_SECRET}
  duration: 900000

snowflake:
   url: ${SNOWFLAKE_URL}
   db: ${SNOWFLAKE_DB}
   name: ${SNOWFLAKE_NAME}
   role: ${SNOWFLAKE_ROLE}
   password: ${SNOWFLAKE_PASSWORD}
   warehouse: ${SNOWFLAKE_WAREHOUSE}
   schema: ${SNOWFLAKE_SCHEMA}

#logging:
#   level:
#     org.springframework.security: DEBUG
